### ISSUE TITLE
Upgrade NGINX Ingress Controller

### ISSUE THREAD

**Issue by gothub** [DataONEorg/k8s-cluster#24]
The current version is ~~[4.0.17](https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.0.17).~~

todo:
- [x] Upgrade on k8s dev 
- [x] verify that all apps are reachable via public URL
   - [x] https://stage.gnis-ld.org/
   - [x] https://api.test.dataone.org/polder/
   - [x] https://api.test.dataone.org/quality
   - [x] https://api.test.dataone.org/slinky
   - [x] https://api.test.dataone.org/purser
- [x] upgrade on production k8s
- [ ] verify that all apps are reachable via public URL
   - [x] https://gnis-ld.org/
   - [x] https://api.dataone.org/slinky
   - [x] https://api.dataone.org/quality

**Comment by gothub** [comment]
Currently on dev:
```
helm list -n ingress-nginx
NAME         	NAMESPACE    	REVISION	UPDATED                               	STATUS  	CHART               	APP VERSION
ingress-nginx	ingress-nginx	1       	2022-02-09 10:28:12.22761881 -0800 PST	deployed	ingress-nginx-4.0.17	1.1.1
```

... prod version is older:
```
helm list -n ingress-nginx
NAME         	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
ingress-nginx	ingress-nginx	1       	2021-12-28 17:01:35.768277057 -0800 PST	deployed	ingress-nginx-4.0.6	1.0.4
```

(from https://kubernetes.github.io/ingress-nginx/deploy/upgrade):

This upgrade should be able to be performed with
```
https://kubernetes.github.io/ingress-nginx/deploy/upgrade/
```

Note that this might cause cert-manager to reissue certs, which might cause service disruption.

**Comment by artntek** [comment]
## Current versions 2/5/25

### dev
```shell
$ helm list -n ingress-nginx                                                              (☸|dev-k8s:default)
NAME           NAMESPACE     REVISION	UPDATED                             	STATUS    CHART                APP VERSION
ingress-nginx ingress-nginx  4       	2022-11-10 17:22:48.759506 -0800 PST	deployed  ingress-nginx-4.0.6  1.0.4
```

### Production
```shell
$ helm list -n ingress-nginx                                                              (☸|prod-k8s:default)
NAME           NAMESPACE     REVISION	UPDATED                                	STATUS    CHART                APP VERSION
ingress-nginx ingress-nginx  1       	2021-12-28 17:01:35.768277057 -0800 PST	deployed  ingress-nginx-4.0.6  1.0.4
```

**Comment by artntek** [comment]
## Notes

See [Peter's installation/upgrade notes](https://github.com/DataONEorg/k8s-cluster/blob/main/control-plane/control-plane.md#Ingress-Controller), but note that for the next upgrade:

* We do NOT need to expose ports `5672` or `8983`
* We do NOT need to expose ports `30080` or `30443`

---

### Explanation from Slack Thread 2/5/25

**Matt said:** The nginx ingress upgrade was done by Peter, and he documented it here if that is helpful to you: https://github.com/DataONEorg/k8s-cluster/blob/main/control-plane/control-plane.md#Ingress-Controller

He said:
> Note that once the additional ports `30080` and `30443` are no longer required by client programs...

In my opinion, those NodePort ports should no longer be needed -- they should have been replaced by ingress-based access. There could still be some URL refs to them in client code, but that should all be changed (the last one I know of was the MetaDIG quality endpoint)

--- 

Matthew Brooke
I notice the TCP services aren't exposed on the prod cluster, only dev.
are you sure we still use those, now that metacat, rmq and solr are all deployed together?

Matt Jones
Yeah, check with Jing. This was needed before to talk to RabbitMQ from outside the cluster
with Metacat inside, may not be needed
We may have a mix for a while though

There are also the TCP Services ports 8983 and 5672 exposed from the dev k8s cluster (Jing can weigh in on that)

Jing said:
I think we don’t need to expose port 8983 and 5672 to the world via ingress. I think it was done when we have a mix system at the early stage of the k8s. Since now everything, metadata, solr, indexer are all in the cluster, there is no reason to do that.

---

Matthew Brooke
For ports 30080 and 30443 -- are you pretty certain they're not needed? Or is there any specific due diligence you can recommend me to do?


Matt Jones
THose were set up before we had an ingress controller working
IN theory, the ingress should be enough
if you ever see a rest endpoint with those ports in one of our client apps, stop and kill it
as I said, the last I knew of was metadig in metacatui, which was updated to the /quality endpoint afaik
I think MetaDIG was the only production service from that time period.... sooo hopefully that's it
I suppose we could watch traffic on the NIC for a bit and see if anything connects to it


Matt Jones
@nick could probably tell us if connections are being made
simplistic view of it looks ok:
```shell
root@docker-ucsb-4:/home/jones# netstat -lt |grep 30080
tcp        0      0 docker-ucsb-4.dat:30080 0.0.0.0:*               LISTEN
root@docker-ucsb-4:/home/jones# netstat -lt |grep 30443
tcp        0      0 docker-ucsb-4.dat:30443 0.0.0.0:*               LISTEN
root@docker-ucsb-4:/home/jones# netstat -t |grep 30443
root@docker-ucsb-4:/home/jones# netstat -t |grep 30080
root@docker-ucsb-4:/home/jones#
```

Maybe grep for those port numbers in our metacatui config files repo?

(MB Note: Did this and fixed them. See [this Metacatui PR](https://github.com/NCEAS/metacatui/pull/2611) and [this metacatui-config PR](https://github.nceas.ucsb.edu/NCEAS/metacatui-config/pull/3)

**Comment by artntek** [comment]
## todo:

- [ ] Decide on version [(see above)](https://github.com/DataONEorg/k8s-cluster/issues/24#issuecomment-2638350044)

- [ ] Upgrade on k8s dev
- verify that all apps are reachable via public URL

  - [ ] https://stage.gnis-ld.org/
  - [ ] https://api.test.dataone.org/quality
  - [ ] https://api.test.dataone.org/purser
  - [ ] test.arcticdata.io
  - [ ] metacat-dev.test.dataone.org
  - [ ] hwitw-dev.arcticdata.io
  - [ ] knb-dev.test.dataone.org

- [ ] upgrade on production k8s
- verify that all apps are reachable via public URL

  - [ ] https://gnis-ld.org/
  - [ ] https://api.dataone.org/quality
  - [ ] arctic-prod.test.dataone.org
  - [ ] purser.dataone.org (nginx welcome page)

**Comment by artntek** [comment]
## Here's what I finally did on dev-k8s:

```shell
# 1. Make a backup, just in case:
helm get manifest -n ingress-nginx ingress-nginx > ingress-nginx-manifest-4.0.6.yaml

# ...this enables disaster recovery, in case upgrade and/or rollback fail; e.g.:
#        $ kubectl apply -f ingress-nginx-manifest-4.0.6.yaml


# 2. leave this running to monitor the changes:
$ watch -n 5 kubectl get all -o wide -n ingress-nginx


# 3. in a separate terminal:
$ helm history ingress-nginx -n ingress-nginx

REVISION  UPDATED                 	STATUS       CHART                  APP VERSION	DESCRIPTION
1         Wed Feb  9 10:28:12 2022	superseded   ingress-nginx-4.0.17   1.1.1      	Install complete
2         Thu Nov 10 16:38:03 2022	superseded   ingress-nginx-4.0.6    1.0.4      	Upgrade complete
3         Thu Nov 10 17:14:36 2022	superseded   ingress-nginx-4.0.6    1.0.4      	Upgrade complete
4         Thu Nov 10 17:22:48 2022	deployed     ingress-nginx-4.0.6    1.0.4      	Upgrade complete


# 4. do a dry run of the upgrade and watch for errors:
#
$ helm upgrade --install ingress-nginx ingress-nginx \
  --version=4.11.4 \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace \
  --set controller.admissionWebhooks.enabled=false \
  --set controller.defaultBackend.enabled=true \
  --set controller.ingressClassResource.default=true \
  --set controller.ingressClassResource.name=nginx \
  --set controller.service.type=NodePort \
  --set controller.service.externalIPs={128.111.85.190} \
  --debug --dry-run

# ...then remove the '--dry-run' flag and do it for real

# Watching the pods, you should see a new one start up, and the old one terminate.

# finally:
#
$ helm history ingress-nginx -n ingress-nginx

REVISION  UPDATED                 	STATUS       CHART                  APP VERSION	DESCRIPTION
1         Wed Feb  9 10:28:12 2022	superseded   ingress-nginx-4.0.17   1.1.1      	Install complete
2         Thu Nov 10 16:38:03 2022	superseded   ingress-nginx-4.0.6    1.0.4      	Upgrade complete
3         Thu Nov 10 17:14:36 2022	superseded   ingress-nginx-4.0.6    1.0.4      	Upgrade complete
4         Thu Nov 10 17:22:48 2022	superseded   ingress-nginx-4.0.6    1.0.4      	Upgrade complete
5         Wed Feb 26 17:32:25 2025	deployed     ingress-nginx-4.11.4   1.11.4     	Upgrade complete

```

**Comment by artntek** [comment]
Revisited this after discussing more with @mbjones. My hypothesis is that the old NodePort service didn't get upgraded by helm because it had been manually edited after the helm install. I therefore tried the following:

1. To delete the service, in the hope helm would re-create it

```shell
## Make a backup just in case:
$ kc get service/ingress-nginx-controller -n ingress-nginx -o yaml > service--ingress-nginx-controller_ORIG.yaml

# then delete...
$ kc delete service/ingress-nginx-controller
```
...however, the service was not re-created. Next step:

2. helm delete the entire chart (now that the service has already gone), then install a fresh copy:

```shell
brooke@magnum-pi.local:~/dev/GITHUB/DataONEorg/k8s-cluster/control-plane/nginx-ingress-controller/2025-upgrade (main) ✗  $ helm delete ingress-nginx -n ingress-nginx                                                                  (☸|dev-k8s:default)
[WARNING] Running a protected command on safe context "dev-k8s". Are you sure? (y/n): y
release "ingress-nginx" uninstalled
brooke@magnum-pi.local:~/dev/GITHUB/DataONEorg/k8s-cluster/control-plane/nginx-ingress-controller/2025-upgrade (main) ✗  $ helm upgrade --install ingress-nginx ingress-nginx \                                                        (☸|dev-k8s:default)
  --version=4.11.4 \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace \
  --set controller.admissionWebhooks.enabled=false \
  --set controller.defaultBackend.enabled=true \
  --set controller.ingressClassResource.default=true \
  --set controller.ingressClassResource.name=nginx \
  --set controller.service.type=NodePort \
  --set controller.service.externalIPs={128.111.85.190} \
  --set controller.allowSnippetAnnotations=true \
  --debug
[WARNING] Running a protected command on safe context "dev-k8s". Are you sure? (y/n): y
history.go:56: 2025-02-27 17:13:01.116194 -0800 PST m=+0.162608751 [debug] getting history for release ingress-nginx
Release "ingress-nginx" does not exist. Installing it now.
install.go:225: 2025-02-27 17:13:01.305004 -0800 PST m=+0.351419626 [debug] Original chart version: "4.11.4"
install.go:242: 2025-02-27 17:13:03.31695 -0800 PST m=+2.363373168 [debug] CHART PATH: /Users/brooke/Library/Caches/helm/repository/ingress-nginx-4.11.4.tgz

client.go:142: 2025-02-27 17:13:04.167277 -0800 PST m=+3.213703210 [debug] creating 1 resource(s)
client.go:142: 2025-02-27 17:13:04.460575 -0800 PST m=+3.507001751 [debug] creating 9 resource(s)
NAME: ingress-nginx
LAST DEPLOYED: Thu Feb 27 17:13:03 2025
NAMESPACE: ingress-nginx
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
[...]
```

Resulting in a new service, with the correct ports:

```shell
$ kc get services -n ingress-nginx                                                   (☸|dev-k8s:default)
NAME                       TYPE       CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
ingress-nginx-controller   NodePort   10.101.123.18   128.111.85.190   80:30679/TCP,443:30544/TCP   34m
```

**Comment by artntek** [comment]
## Prod Cluster NGinx Upgrade

### Starting state:

```shell
$ helm history -n ingress-nginx ingress-nginx
REVISION  UPDATED                   STATUS    CHART                APP VERSION  DESCRIPTION
1         Tue Dec 28 17:01:35 2021  deployed  ingress-nginx-4.0.6  1.0.4        Install complete
```

**Comment by artntek** [comment]
Upgraded both dev and prod to ingress-nginx chart v4.11.6 (app v1.11.6), and set `controller.admissionWebhooks.enabled=true`

Note we can't upgrade to chart 1.12.* until we upgrade k8s to 1.28 or higher
